language: node_js
notifications:
  email: false
node_js:
  - '12'
before_script:
  - npm prune
script:
  - npm run test
  - npm run build:lib
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
git:
  depth: 200