name: Build, Test & Release Styleguide

on:
  push:
    branches:
      - master

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: npm prune
    - run: npm install
    - run: npm run test
    - run: npm run build:lib
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run semantic-release
